### ISSUE TITLE
Laser Designators (handheld) not storing in Arsenal

### ISSUE THREAD

**Issue by PoweredByPot** [official-antistasi-community/A3-Antistasi-1.4#65]
A single pair was in a crate I stole, stuffed it into the arsenal and it is nowhere to be found.

**Comment by PoweredByPot** [comment]
They are actually being shown to the player under "Misc Items" when loading things into clothing.

**Comment by Spoffy** [comment]
This has coincidentally been fixed in 9d77f33cef24268b236d559810fc89157687e221. Arsenal categorisation code was totally rewritten.

**Comment by PoweredByPot** [comment]
@Spoffy this is the only arsenal weirdness I still see. Laser Designators are still under 'Misc Items' that go in clothing.

**Comment by Spoffy** [comment]
Which laser designators? I loaded a handful in and had no issues.
